### ISSUE TITLE
traverse_flat not the same as [] operator

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/docarray#183]
```python
from jina import DocumentArray, Document

da = DocumentArray([Document(text='Hello. World! Go? Back')])
da['@r']
da.traverse_flat('@r')
```

this fails with

```python
Traceback (most recent call last):
  File "/home/cristian/.config/JetBrains/PyCharm2021.3/scratches/scratch_16.py", line 5, in <module>
    da.traverse_flat('@r')
  File "/home/cristian/.virtualenvs/executors30/lib/python3.7/site-packages/docarray/array/mixins/traverse.py", line 120, in traverse_flat
    return self._flatten(leaves)
  File "/home/cristian/.virtualenvs/executors30/lib/python3.7/site-packages/docarray/array/mixins/traverse.py", line 159, in _flatten
    return DocumentArray(list(itertools.chain.from_iterable(sequence)))
  File "/home/cristian/.virtualenvs/executors30/lib/python3.7/site-packages/docarray/array/mixins/traverse.py", line 46, in traverse
    yield from self._traverse(self, p, filter_fn=filter_fn)
  File "/home/cristian/.virtualenvs/executors30/lib/python3.7/site-packages/docarray/array/mixins/traverse.py", line 56, in _traverse
    cur_loc, cur_slice, _left = _parse_path_string(path)
  File "/home/cristian/.virtualenvs/executors30/lib/python3.7/site-packages/docarray/array/mixins/traverse.py", line 164, in _parse_path_string
    _this = g.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```

`docarray==0.7.2`

**Comment by davidbp** [comment]
```

**Comment by hanxiao** [comment]
`traverse_flat` is not a supported Public function in docarray
